### ISSUE TITLE
How to get this running in windows 10

### ISSUE THREAD

**Issue by githubtrip** [dangolbeeker/2021RedditAccountCreateandUpvote#1]
Not able to get this setup and running in windows 10. How to get this thing running?

**Comment by dangolbeeker** [comment]
You will need to download the Tor Browser. 
https://www.torproject.org/download/

*Note: You have to keep running tor browser for this

Navigate to \Tor Browser\Browser\TorBrowser\Data\Tor and edit torcc file

# ControlPort 9051
SocksPort 9051
restart tor

use tor proxy everywhere:
control panel -> network & internet -> internet options -> connection -> lan setting -> tick proxy server & goto advance & add:

proxy 127.0.0.1 port 9051
use tor proxy in a browser like firefox:
options -> network setting -> tick Manual proxy configuration & add:

proxy 127.0.0.1 port 9051
use with python requests library:
import requests

proxies = {
    'http':'socks5://127.0.0.1:9051',
    'https':'socks5:/127.0.0.1:9051'
}
url = 'https://check.torproject.org/'
res = requests.get(url, proxies=proxies)

**Comment by dangolbeeker** [comment]
Prerequisites Firefox browser. You must have the Tor service installed and running for this to propery work. Reddit limits account creation from individual IP addresses and Tor allows you to get around this.

sudo apt-get install tor Selenium You must also have Selenium installed.

pip install selenium This may or may not be an issue for you, but Seleinum would not run properly with Firefox on my system. I had to update my geckowebdriver by moving the most recent version into /usr/local/bin/.

Instructions randomUsernames.py This file will generate a text file will 100 random usernames and passwords in the format of username:password.

creator.py This file will create your accounts. When run it will open firefox using tor and enter the first username:password combo from 'redditNameList.txt' into Reddits's account creator. The program will now pause and wait for you to solve the captcha and Press 'sign up'. After you have done this, press enter and that username:password combo will be removed from 'redditNameList.txt' and moved to 'createdNames.txt'. Tor will restart to bypass Reddit's IP limiting. You can repeat this process until you have as many accounts as you want or need.

Note: Ocassionally the Captcha will not appear. I'm not sure why this happens, but if you move to a new IP it seems to resolve itself. If you press 'r' then 'enter' instead of just 'enter', it will skip the current username:password combo leaving it in 'redditNameList.txt' and not moving it to 'createdNames.txt'.

upvoter.py This file allows you to upvote posts or comments. You must enter the link to the post or comment at the top of the file in 'postLink' or 'commentPermaLink' variable. You must also comment out the function call you are not preforming in main. When ran, this will iterate through 'createdNames.txt' signing in each account, upvoting, then moving to the next account. Tor is not used in this file as I didn't notice any vote limiting.
